<?php

declare(strict_types=1);

require __DIR__.'/_init.php';$admin=require_super_admin();
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{
        admin_post_guard();$id=filter_var($_POST['id']??null,FILTER_VALIDATE_INT)?:null;$name=trim((string)($_POST['name']??''));$email=normalize_email((string)($_POST['email']??''));$role=(string)($_POST['role']??'ADMIN');$active=isset($_POST['active']);$password=(string)($_POST['password']??'');
        if(mb_strlen($name)<2||!filter_var($email,FILTER_VALIDATE_EMAIL)||!in_array($role,['SUPER_ADMIN','ADMIN'],true))throw new DomainException('Enter a valid name, email, and role.');
        if($id===null){if(strlen($password)<12)throw new DomainException('New admin passwords must be at least 12 characters.');$id=admin_repository()->createAdmin($name,$email,password_hash($password,PASSWORD_DEFAULT),$role);admin_repository()->audit((int)$admin['id'],'admin.create','admin',$id,'Created '.$role.' account for '.$email.'.');flash('success','Admin created.');}
        else{$target=admin_repository()->findAdminById((int)$id);if(!$target)throw new DomainException('Admin not found.');if((int)$target['id']===(int)$admin['id']&&!$active)throw new DomainException('You cannot disable your current admin account.');if($target['role']==='SUPER_ADMIN'&&($role!=='SUPER_ADMIN'||!$active)&&admin_repository()->countActiveSuperAdmins()<=1)throw new DomainException('The only active super admin cannot be disabled or demoted.');admin_repository()->updateAdmin((int)$id,$name,$email,$role,$active);if($password!==''){if(strlen($password)<12)throw new DomainException('Admin passwords must be at least 12 characters.');admin_repository()->updateAdminPassword((int)$id,password_hash($password,PASSWORD_DEFAULT));}admin_repository()->audit((int)$admin['id'],'admin.update','admin',(int)$id,'Updated admin account '.$email.'.');flash('success','Admin updated.');}
    }catch(Throwable$exception){admin_flash_exception($exception);}admin_redirect('admins.php');
}
$rows=admin_repository()->admins();$editId=filter_var($_GET['edit']??null,FILTER_VALIDATE_INT)?:null;$edit=null;foreach($rows as$row)if((int)$row['id']===$editId)$edit=$row;
$adminTitle='Admins';$adminPage='admins';$adminSection='System';require __DIR__.'/_header.php';
?>
<div class="detail-grid"><section class="panel"><header class="panel__header"><h2>Administrator accounts</h2><span><?= count($rows) ?> total</span></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Admin</th><th>Role</th><th>Status</th><th>Last login</th><th>Created</th><th></th></tr></thead><tbody><?php foreach($rows as$row): ?><tr><td><strong><?= e((string)$row['name']) ?></strong><small><?= e((string)$row['email']) ?></small></td><td><span class="status <?= $row['role']==='SUPER_ADMIN'?'status--active':'' ?>"><?= e(format_status((string)$row['role'])) ?></span></td><td><span class="<?= e(admin_status_class($row['active']?'active':'disabled')) ?>"><?= $row['active']?'Active':'Disabled' ?></span></td><td><?= e((string)($row['last_login_at']??'Never')) ?></td><td><?= e(date('M j, Y',strtotime((string)$row['created_at']))) ?></td><td class="actions"><a class="button button--small button--quiet" href="?edit=<?= (int)$row['id'] ?>">Edit</a></td></tr><?php endforeach; ?></tbody></table></div></section>
<aside><form method="post" class="form-section form-stack sticky-card" <?= $edit?'data-confirm="Apply these admin access changes?"':'' ?>><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><h2><?= $edit?'Edit':'Add' ?> admin</h2><label class="field"><span>Name</span><input name="name" value="<?= e((string)($edit['name']??'')) ?>" required></label><label class="field"><span>Email</span><input type="email" name="email" value="<?= e((string)($edit['email']??'')) ?>" required></label><label class="field"><span>Role</span><select name="role"><option value="ADMIN" <?= ($edit['role']??'ADMIN')==='ADMIN'?'selected':'' ?>>Admin</option><option value="SUPER_ADMIN" <?= ($edit['role']??'')==='SUPER_ADMIN'?'selected':'' ?>>Super admin</option></select></label><label class="field"><span><?= $edit?'New password':'Password' ?></span><input type="password" name="password" minlength="12" autocomplete="new-password" <?= $edit?'':'required' ?>><small><?= $edit?'Leave blank to keep the current password.':'Minimum 12 characters.' ?></small></label><label class="check-field"><input type="checkbox" name="active" value="1" <?= !isset($edit['active'])||$edit['active']?'checked':'' ?>> Active</label><div class="form-footer"><?php if($edit): ?><a class="button button--quiet" href="admins.php">Cancel</a><?php endif; ?><button class="button button--primary" type="submit">Save admin</button></div></form></aside></div>
<?php require __DIR__.'/_footer.php'; ?>
