<?php

declare(strict_types=1);

require __DIR__.'/_init.php';require_admin();$range=admin_range((string)($_GET['range']??'all'));$data=admin_repository()->analytics($range['since']);$k=$data['kpis'];$adminTitle='Analytics';$adminPage='analytics';$adminSection='Reports';$adminActions='<div class="page-actions"><div class="range-tabs">';foreach(['today'=>'Today','7d'=>'7 Days','30d'=>'30 Days','month'=>'This Month','all'=>'All Time']as$key=>$label)$adminActions.='<a class="'.($range['key']===$key?'is-active':'').'" href="?range='.$key.'">'.$label.'</a>';$adminActions.='</div></div>';require __DIR__.'/_header.php';
$maxCategory=max(array_map(static fn($r)=>(float)$r['revenue'],$data['categories'])?:[1]);$maxCollection=max(array_map(static fn($r)=>(float)$r['revenue'],$data['collections'])?:[1]);
?>
<section class="kpi-grid"><article class="kpi"><span>Revenue</span><strong><?= admin_money($k['revenue']) ?></strong><small><?= e($range['label']) ?></small></article><article class="kpi"><span>Orders</span><strong><?= (int)$k['orders'] ?></strong></article><article class="kpi"><span>Average order</span><strong><?= admin_money($k['aov']) ?></strong></article><article class="kpi"><span>New customers</span><strong><?= (int)$k['customers'] ?></strong></article></section>
<section class="panel" style="margin-bottom:1rem"><header class="panel__header"><h2>Monthly revenue</h2><span>Paid orders</span></header><div class="chart-wrap"><canvas data-chart-source="monthly-series" role="img" aria-label="Monthly revenue chart"></canvas><script type="application/json" id="monthly-series"><?= json_encode($data['monthly'],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script></div></section>
<div class="dashboard-grid"><section class="panel"><header class="panel__header"><h2>Sales by category</h2></header><div class="panel__body bar-list"><?php foreach($data['categories']as$row): ?><div class="bar-row"><span><?= e((string)$row['label']) ?></span><div class="bar-track"><span style="width:<?= round((float)$row['revenue']/$maxCategory*100) ?>%"></span></div><strong><?= admin_money($row['revenue']) ?></strong></div><?php endforeach; ?><?php if(!$data['categories']): ?><div class="empty-state"><p>No sales in this range.</p></div><?php endif; ?></div></section><section class="panel"><header class="panel__header"><h2>Sales by collection</h2></header><div class="panel__body bar-list"><?php foreach($data['collections']as$row): ?><div class="bar-row"><span><?= e((string)$row['label']) ?></span><div class="bar-track"><span style="width:<?= round((float)$row['revenue']/$maxCollection*100) ?>%"></span></div><strong><?= admin_money($row['revenue']) ?></strong></div><?php endforeach; ?><?php if(!$data['collections']): ?><div class="empty-state"><p>No sales in this range.</p></div><?php endif; ?></div></section></div>
<div class="dashboard-grid"><section class="panel"><header class="panel__header"><h2>Best-selling products</h2></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Product</th><th class="numeric">Units</th><th class="numeric">Sales</th></tr></thead><tbody><?php foreach($data['best_sellers']as$row): ?><tr><td><strong><?= e((string)$row['name']) ?></strong></td><td class="numeric"><?= (int)$row['units'] ?></td><td class="numeric"><?= admin_money($row['revenue']) ?></td></tr><?php endforeach; ?></tbody></table></div></section><section class="panel"><header class="panel__header"><h2>Order distribution</h2></header><div class="panel__body"><?php foreach($data['status_summary']as$row): ?><div class="bar-row"><span><?= e(format_status((string)$row['status'])) ?></span><div></div><strong><?= (int)$row['count'] ?></strong></div><?php endforeach; ?></div></section></div>
<?php require __DIR__.'/_footer.php'; ?>
