<?php

declare(strict_types=1);

require __DIR__.'/_init.php';require_admin();
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{admin_post_guard();admin_service()->saveCoupon($_POST,filter_var($_POST['id']??null,FILTER_VALIDATE_INT)?:null);flash('success','Coupon saved.');}
    catch(Throwable$exception){admin_flash_exception($exception);}admin_redirect('coupons.php');
}
$filters=['q'=>(string)($_GET['q']??'')];$result=admin_repository()->coupons($filters,(int)($_GET['page']??1));$editId=filter_var($_GET['edit']??null,FILTER_VALIDATE_INT)?:null;$edit=$editId?admin_repository()->coupon((int)$editId):null;
$dateValue=static fn($value):string=>$value?date('Y-m-d\TH:i',strtotime((string)$value)):'';$adminTitle='Coupons';$adminPage='coupons';$adminSection='Sales';require __DIR__.'/_header.php';
?>
<form class="toolbar" method="get"><label class="field field--search"><span>Search</span><input type="search" name="q" value="<?= e($filters['q']) ?>" placeholder="Coupon code"></label><div class="toolbar-actions"><button class="button" type="submit">Filter</button><a class="button button--quiet" href="coupons.php">Reset</a></div></form>
<div class="detail-grid"><section class="panel"><header class="panel__header"><h2><?= number_format($result['total']) ?> coupons</h2></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Code</th><th>Discount</th><th class="numeric">Minimum</th><th>Dates</th><th class="numeric">Usage</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($result['items']as$row): $expired=$row['expires_at']&&strtotime((string)$row['expires_at'])<time();?><tr><td><strong><?= e((string)$row['code']) ?></strong></td><td><?= e($row['type']==='percentage'?rtrim(rtrim((string)$row['value'],'0'),'.').'%':admin_money($row['value'])) ?></td><td class="numeric"><?= admin_money($row['minimum_order']) ?></td><td><small><?= $row['starts_at']?'From '.e((string)$row['starts_at']):'Immediate' ?><br><?= $row['expires_at']?'Until '.e((string)$row['expires_at']):'No expiry' ?></small></td><td class="numeric"><?= (int)$row['usage_count'] ?><?= $row['usage_limit']?' / '.(int)$row['usage_limit']:'' ?></td><td><span class="<?= e(admin_status_class($expired?'archived':($row['is_active']?'active':'disabled'))) ?>"><?= $expired?'Expired':($row['is_active']?'Active':'Disabled') ?></span></td><td class="actions"><a class="button button--small button--quiet" href="?edit=<?= (int)$row['id'] ?>">Edit</a></td></tr><?php endforeach; ?></tbody></table></div></section>
<aside><form class="form-section form-stack sticky-card" method="post"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><h2><?= $edit?'Edit':'Add' ?> coupon</h2><label class="field"><span>Code</span><input name="code" maxlength="60" value="<?= e((string)($edit['code']??'')) ?>" required></label><div class="field-row"><label class="field"><span>Type</span><select name="type"><option value="percentage" <?= ($edit['type']??'percentage')==='percentage'?'selected':'' ?>>Percentage</option><option value="fixed" <?= ($edit['type']??'')==='fixed'?'selected':'' ?>>Fixed amount</option></select></label><label class="field"><span>Value</span><input type="number" min="0.01" step="0.01" name="value" value="<?= e((string)($edit['value']??'')) ?>" required></label></div><label class="field"><span>Minimum order</span><input type="number" min="0" step="0.01" name="minimum_order" value="<?= e((string)($edit['minimum_order']??0)) ?>"></label><div class="field-row"><label class="field"><span>Starts at</span><input type="datetime-local" name="starts_at" value="<?= e($dateValue($edit['starts_at']??null)) ?>"></label><label class="field"><span>Expires at</span><input type="datetime-local" name="expires_at" value="<?= e($dateValue($edit['expires_at']??null)) ?>"></label></div><div class="field-row"><label class="field"><span>Global limit</span><input type="number" min="1" name="usage_limit" value="<?= e((string)($edit['usage_limit']??'')) ?>"></label><label class="field"><span>Per-customer limit</span><input type="number" min="1" name="per_customer_limit" value="<?= e((string)($edit['per_customer_limit']??'')) ?>"></label></div><label class="check-field"><input type="checkbox" name="is_active" value="1" <?= !isset($edit['is_active'])||$edit['is_active']?'checked':'' ?>> Active</label><div class="form-footer"><?php if($edit): ?><a class="button button--quiet" href="coupons.php">Cancel</a><?php endif; ?><button class="button button--primary" type="submit">Save coupon</button></div></form></aside></div><?= admin_pagination($result) ?>
<?php require __DIR__.'/_footer.php'; ?>
