<?php

declare(strict_types=1);

require __DIR__.'/_init.php';$admin=require_admin();$id=(int)($_GET['id']??$_POST['id']??0);
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{admin_post_guard();$status=(string)($_POST['status']??'');if(!in_array($status,['active','disabled'],true))throw new DomainException('Choose a valid customer status.');admin_repository()->updateCustomerStatus($id,$status);admin_repository()->audit((int)$admin['id'],'customer.status','customer',$id,'Customer status changed to '.$status.'.');flash('success','Customer status updated.');}
    catch(Throwable$exception){admin_flash_exception($exception);}admin_redirect('customer.php?id='.$id);
}
$customer=admin_repository()->customer($id);if(!$customer){http_response_code(404);exit('Customer not found.');}$adminTitle=$customer['first_name'].' '.$customer['last_name'];$adminPage='customers';$adminSection='Sales / Customers';$adminActions='<div class="page-actions"><a class="button button--quiet" href="'.e(url('admin/customers.php')).'">Back to customers</a></div>';require __DIR__.'/_header.php';
?>
<section class="kpi-grid"><article class="kpi"><span>Lifetime spend</span><strong><?= admin_money($customer['lifetime_spend']) ?></strong></article><article class="kpi"><span>Orders</span><strong><?= (int)$customer['orders_count'] ?></strong></article><article class="kpi"><span>Wishlist</span><strong><?= (int)$customer['wishlist_count'] ?></strong></article><article class="kpi"><span>Reviews</span><strong><?= (int)$customer['review_count'] ?></strong></article></section>
<div class="detail-grid"><div><section class="panel"><header class="panel__header"><h2>Profile</h2><span class="<?= e(admin_status_class((string)$customer['status'])) ?>"><?= e(format_status((string)$customer['status'])) ?></span></header><div class="panel__body"><dl class="definition-list"><dt>Name</dt><dd><?= e($customer['first_name'].' '.$customer['last_name']) ?></dd><dt>Email</dt><dd><a href="mailto:<?= e((string)$customer['email']) ?>"><?= e((string)$customer['email']) ?></a></dd><dt>Joined</dt><dd><?= e((string)$customer['created_at']) ?></dd><dt>Last login</dt><dd><?= e((string)($customer['last_login_at']??'Never')) ?></dd></dl></div></section>
<section class="panel" style="margin-top:1rem"><header class="panel__header"><h2>Addresses</h2><span><?= count($customer['addresses']) ?></span></header><div class="panel__body"><?php foreach($customer['addresses']as$address): ?><article style="padding:.8rem 0;border-bottom:1px solid var(--line)"><strong><?= e((string)$address['label']) ?><?= $address['is_default']?' · Default':'' ?></strong><p><?= e((string)$address['recipient_name']) ?> · <?= e((string)$address['phone']) ?><br><?= e((string)$address['address_line_1']) ?><?= $address['address_line_2']?'<br>'.e((string)$address['address_line_2']):'' ?><br><?= e($address['city'].', '.$address['province'].' '.$address['postal_code']) ?> · <?= e((string)$address['country']) ?></p></article><?php endforeach; ?><?php if(!$customer['addresses']): ?><p>No saved addresses.</p><?php endif; ?></div></section>
<section class="panel" style="margin-top:1rem"><header class="panel__header"><h2>Order history</h2></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Order</th><th>Date</th><th>Payment</th><th>Status</th><th class="numeric">Total</th></tr></thead><tbody><?php foreach($customer['orders']as$order): ?><tr><td><a href="<?= e(url('admin/order.php?id='.(int)$order['id'])) ?>"><strong><?= e((string)$order['order_number']) ?></strong></a></td><td><?= e((string)$order['placed_at']) ?></td><td><span class="<?= e(admin_status_class((string)$order['payment_status'])) ?>"><?= e(format_status((string)$order['payment_status'])) ?></span></td><td><span class="<?= e(admin_status_class((string)$order['order_status'])) ?>"><?= e(format_status((string)$order['order_status'])) ?></span></td><td class="numeric"><?= admin_money($order['total']) ?></td></tr><?php endforeach; ?></tbody></table></div></section></div>
<aside><form class="form-section form-stack sticky-card" method="post" data-confirm="Change this customer’s account access?"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$id ?>"><h2>Account status</h2><p>Disabling access preserves addresses, orders, wishlists, and reviews.</p><label class="field"><span>Status</span><select name="status"><option value="active" <?= $customer['status']==='active'?'selected':'' ?>>Active</option><option value="disabled" <?= $customer['status']==='disabled'?'selected':'' ?>>Disabled</option></select></label><button class="button button--primary" type="submit">Update status</button></form></aside></div>
<?php require __DIR__.'/_footer.php'; ?>
