<?php

declare(strict_types=1);

require __DIR__.'/_init.php';require_admin();$filters=['q'=>(string)($_GET['q']??''),'status'=>(string)($_GET['status']??'')];$result=admin_repository()->customers($filters,(int)($_GET['page']??1));
$adminTitle='Customers';$adminPage='customers';$adminSection='Sales';$adminActions='<div class="page-actions"><a class="button button--quiet" href="'.e(url('admin/export.php?type=customers')).'">Export CSV</a></div>';require __DIR__.'/_header.php';
?>
<form class="toolbar" method="get"><label class="field field--search"><span>Search</span><input type="search" name="q" value="<?= e($filters['q']) ?>" placeholder="Name or email"></label><label class="field"><span>Status</span><select name="status"><option value="">All customers</option><option value="active" <?= $filters['status']==='active'?'selected':'' ?>>Active</option><option value="disabled" <?= $filters['status']==='disabled'?'selected':'' ?>>Disabled</option></select></label><div class="toolbar-actions"><button class="button" type="submit">Filter</button><a class="button button--quiet" href="customers.php">Reset</a></div></form>
<section class="panel"><header class="panel__header"><h2><?= number_format($result['total']) ?> customers</h2></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Customer</th><th>Email</th><th>Joined</th><th class="numeric">Orders</th><th class="numeric">Total spend</th><th>Last order</th><th>Status</th></tr></thead><tbody><?php foreach($result['items']as$user): ?><tr><td><a href="<?= e(url('admin/customer.php?id='.(int)$user['id'])) ?>"><strong><?= e($user['first_name'].' '.$user['last_name']) ?></strong></a></td><td><?= e((string)$user['email']) ?></td><td><?= e(date('M j, Y',strtotime((string)$user['created_at']))) ?></td><td class="numeric"><?= (int)$user['orders_count'] ?></td><td class="numeric"><strong><?= admin_money($user['total_spend']) ?></strong></td><td><?= $user['last_order_at']?e(date('M j, Y',strtotime((string)$user['last_order_at']))):'—' ?></td><td><span class="<?= e(admin_status_class((string)$user['status'])) ?>"><?= e(format_status((string)$user['status'])) ?></span></td></tr><?php endforeach; ?></tbody></table><?php if(!$result['items']): ?><div class="empty-state"><div><strong>No customers found</strong><p>Adjust the filters.</p></div></div><?php endif; ?></div></section><?= admin_pagination($result) ?>
<?php require __DIR__.'/_footer.php'; ?>
