<?php

declare(strict_types=1);

require __DIR__.'/_init.php';require_admin();$range=admin_range((string)($_GET['range']??'30d'));$data=admin_repository()->dashboard($range['since']);$k=$data['kpis'];
$adminTitle='Dashboard';$adminPage='dashboard';$adminSection='Dashboard';
$adminActions='<div class="page-actions"><div class="range-tabs" aria-label="Analytics range">';
foreach(['today'=>'Today','7d'=>'7 Days','30d'=>'30 Days','month'=>'This Month','all'=>'All Time']as$key=>$label)$adminActions.='<a class="'.($range['key']===$key?'is-active':'').'" href="?range='.$key.'">'.$label.'</a>';
$adminActions.='</div></div>';require __DIR__.'/_header.php';$maxSeller=max(array_map(static fn($r)=>(int)$r['units'],$data['best_sellers'])?:[1]);
?>
<section class="kpi-grid" aria-label="Store KPIs">
<article class="kpi"><span>Revenue · <?= e($range['label']) ?></span><strong><?= admin_money($k['revenue']) ?></strong><small>Paid, non-cancelled orders</small></article>
<article class="kpi"><span>Orders</span><strong><?= number_format((int)$k['orders']) ?></strong><small>Non-cancelled</small></article>
<article class="kpi"><span>Average order</span><strong><?= admin_money($k['aov']) ?></strong><small>Selected range</small></article>
<article class="kpi"><span>Customers</span><strong><?= number_format((int)$k['customers']) ?></strong><small>Joined in range</small></article>
<article class="kpi"><span>Products</span><strong><?= number_format((int)$k['products']) ?></strong><small>Active catalog</small></article>
<article class="kpi kpi--alert"><span>Low / out stock</span><strong><?= number_format((int)$k['low_stock']) ?></strong><small>At threshold <?= e(setting('low_stock_threshold','5')) ?></small></article>
<article class="kpi"><span>Open orders</span><strong><?= number_format((int)$k['pending_orders']) ?></strong><small>Pending or processing</small></article>
<article class="kpi"><span>Pending reviews</span><strong><?= number_format((int)$k['pending_reviews']) ?></strong><small>Awaiting moderation</small></article>
</section>
<div class="dashboard-grid"><section class="panel"><header class="panel__header"><h2>Revenue trend</h2><span class="status"><?= e($range['label']) ?></span></header><div class="chart-wrap"><canvas data-chart-source="revenue-series" role="img" aria-label="Revenue trend chart"></canvas><script type="application/json" id="revenue-series"><?= json_encode($data['revenue_series'],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script></div></section>
<section class="panel"><header class="panel__header"><h2>Order status</h2><a href="<?= e(url('admin/orders.php')) ?>">View orders</a></header><div class="panel__body bar-list"><?php if(!$data['status_summary']): ?><div class="empty-state"><p>No orders in this range.</p></div><?php else:$maxStatus=max(array_map(static fn($r)=>(int)$r['count'],$data['status_summary']));foreach($data['status_summary']as$row): ?><div class="bar-row"><span><?= e(format_status((string)$row['status'])) ?></span><div class="bar-track"><span style="width:<?= $maxStatus?round((int)$row['count']/$maxStatus*100):0 ?>%"></span></div><strong><?= (int)$row['count'] ?></strong></div><?php endforeach;endif; ?></div></section></div>
<div class="dashboard-grid"><section class="panel"><header class="panel__header"><h2>Recent orders</h2><a href="<?= e(url('admin/orders.php')) ?>">All orders</a></header><div class="panel__body--flush table-wrap"><table class="data-table"><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Status</th><th class="numeric">Total</th></tr></thead><tbody><?php foreach($data['recent_orders']as$order): ?><tr><td><a href="<?= e(url('admin/order.php?id='.(int)$order['id'])) ?>"><strong><?= e((string)$order['order_number']) ?></strong></a></td><td><?= e($order['customer_first_name'].' '.$order['customer_last_name']) ?></td><td><?= e(date('M j, Y',strtotime((string)$order['placed_at']))) ?></td><td><span class="<?= e(admin_status_class((string)$order['order_status'])) ?>"><?= e(format_status((string)$order['order_status'])) ?></span></td><td class="numeric"><?= admin_money($order['total']) ?></td></tr><?php endforeach; ?></tbody></table><?php if(!$data['recent_orders']): ?><div class="empty-state"><p>No orders yet.</p></div><?php endif; ?></div></section>
<section class="panel"><header class="panel__header"><h2>Best sellers</h2><a href="<?= e(url('admin/analytics.php')) ?>">Analytics</a></header><div class="panel__body bar-list"><?php if(!$data['best_sellers']): ?><div class="empty-state"><p>No sales in this range.</p></div><?php else:foreach($data['best_sellers']as$row): ?><div class="bar-row"><span><?= e((string)$row['name']) ?></span><div class="bar-track"><span style="width:<?= round((int)$row['units']/$maxSeller*100) ?>%"></span></div><strong><?= (int)$row['units'] ?></strong></div><?php endforeach;endif; ?></div></section></div>
<section class="panel"><header class="panel__header"><h2>Stock watch</h2><a href="<?= e(url('admin/inventory.php?stock=low')) ?>">Open inventory</a></header><div class="panel__body--flush table-wrap"><table class="data-table"><thead><tr><th>SKU</th><th>Product</th><th>Variant</th><th class="numeric">Stock</th></tr></thead><tbody><?php foreach($data['low_stock']as$row): ?><tr><td><strong><?= e((string)$row['sku']) ?></strong></td><td><?= e((string)$row['product_name']) ?></td><td><?= e($row['color_name'].' / '.$row['size']) ?></td><td class="numeric <?= (int)$row['stock_quantity']===0?'stock-out':'stock-low' ?>"><strong><?= (int)$row['stock_quantity'] ?></strong></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php require __DIR__.'/_footer.php'; ?>
