<?php

declare(strict_types=1);

require __DIR__.'/_init.php';require_admin();
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{admin_post_guard();$new=admin_service()->adjustStock((int)($_POST['variant_id']??0),(int)($_POST['change_amount']??0),(string)($_POST['reason']??''),(string)($_POST['note']??''));flash('success','Stock updated to '.$new.'.');}
    catch(Throwable$exception){admin_flash_exception($exception);}admin_redirect('inventory.php'.(!empty($_SERVER['QUERY_STRING'])?'?'.$_SERVER['QUERY_STRING']:''));
}
$filters=['q'=>(string)($_GET['q']??''),'stock'=>(string)($_GET['stock']??''),'active'=>(string)($_GET['active']??''),'sort'=>(string)($_GET['sort']??'stock')];$result=admin_repository()->inventory($filters,(int)($_GET['page']??1));
$adminTitle='Inventory';$adminPage='inventory';$adminSection='Store';$adminActions='<div class="page-actions"><a class="button button--quiet" href="'.e(url('admin/export.php?type=inventory')).'">Export CSV</a></div>';require __DIR__.'/_header.php';$threshold=(int)setting('low_stock_threshold','5');
?>
<form class="toolbar" method="get"><label class="field field--search"><span>Search</span><input type="search" name="q" value="<?= e($filters['q']) ?>" placeholder="SKU, product, color, or size"></label><label class="field"><span>Stock</span><select name="stock"><option value="">All stock</option><option value="low" <?= $filters['stock']==='low'?'selected':'' ?>>Low stock only</option><option value="out" <?= $filters['stock']==='out'?'selected':'' ?>>Out of stock only</option></select></label><label class="field"><span>Variant status</span><select name="active"><option value="">All</option><option value="active" <?= $filters['active']==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= $filters['active']==='inactive'?'selected':'' ?>>Inactive</option></select></label><label class="field"><span>Sort</span><select name="sort"><option value="stock">Lowest stock</option><option value="updated" <?= $filters['sort']==='updated'?'selected':'' ?>>Recently updated</option><option value="product" <?= $filters['sort']==='product'?'selected':'' ?>>Product</option><option value="sku" <?= $filters['sort']==='sku'?'selected':'' ?>>SKU</option></select></label><div class="toolbar-actions"><button class="button" type="submit">Filter</button><a class="button button--quiet" href="inventory.php">Reset</a></div></form>
<section class="panel"><header class="panel__header"><h2><?= number_format($result['total']) ?> variants</h2><span>Low stock threshold: <?= $threshold ?></span></header><div class="table-wrap"><table class="data-table"><thead><tr><th>SKU</th><th>Product</th><th>Variant</th><th class="numeric">Current stock</th><th>Stock state</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($result['items']as$row): $stock=(int)$row['stock_quantity'];?><tr><td><strong><?= e((string)$row['sku']) ?></strong></td><td><a href="<?= e(url('admin/product-edit.php?id='.(int)$row['product_id'].'&tab=variants')) ?>"><?= e((string)$row['product_name']) ?></a><small><?= e(format_status((string)$row['product_status'])) ?></small></td><td><?= e($row['color_name'].' / '.$row['size']) ?></td><td class="numeric <?= $stock===0?'stock-out':($stock<=$threshold?'stock-low':'') ?>"><strong><?= $stock ?></strong></td><td><span class="<?= e(admin_status_class($stock===0?'out':($stock<=$threshold?'pending':'active'))) ?>"><?= $stock===0?'Out of stock':($stock<=$threshold?'Low stock':'In stock') ?></span></td><td><span class="<?= e(admin_status_class($row['is_active']?'active':'disabled')) ?>"><?= $row['is_active']?'Active':'Disabled' ?></span></td><td class="actions"><button class="button button--small button--primary" type="button" data-dialog-open data-variant-id="<?= (int)$row['id'] ?>" data-variant-label="<?= e($row['sku'].' · '.$row['product_name']) ?>">Adjust</button></td></tr><?php endforeach; ?></tbody></table><?php if(!$result['items']): ?><div class="empty-state"><div><strong>No variants found</strong><p>Adjust your filters.</p></div></div><?php endif; ?></div></section><?= admin_pagination($result) ?>
<dialog data-dialog aria-labelledby="stock-dialog-title"><form method="post"><?= csrf_field() ?><div class="dialog__header"><h2 id="stock-dialog-title" data-dialog-label>Stock adjustment</h2><button class="icon-button" type="button" data-dialog-close aria-label="Close">×</button></div><div class="dialog__body"><input type="hidden" name="variant_id"><label class="field"><span>Change amount</span><input type="number" name="change_amount" required placeholder="Use -2 or 12"><small>Positive values add stock. Negative values remove stock.</small></label><label class="field"><span>Reason</span><select name="reason" required><option value="restock">Restock</option><option value="correction">Correction</option><option value="return">Return</option><option value="damage">Damage</option><option value="manual_adjustment">Manual adjustment</option></select></label><label class="field"><span>Note</span><input name="note" maxlength="255" placeholder="Optional audit note"></label></div><div class="dialog__footer"><button class="button button--quiet" type="button" data-dialog-close>Cancel</button><button class="button button--primary" type="submit">Apply adjustment</button></div></form></dialog>
<?php require __DIR__.'/_footer.php'; ?>
