<?php

declare(strict_types=1);

require __DIR__.'/_init.php';$admin=require_admin();
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{admin_post_guard();$id=(int)($_POST['id']??0);$status=(string)($_POST['status']??'');if(!in_array($status,['subscribed','unsubscribed'],true))throw new DomainException('Choose a valid subscriber status.');admin_repository()->updateSubscriberStatus($id,$status);admin_repository()->audit((int)$admin['id'],'newsletter.status','subscriber',$id,'Subscriber changed to '.$status.'.');flash('success','Subscriber updated.');}
    catch(Throwable$exception){admin_flash_exception($exception);}admin_redirect('newsletter.php'.(!empty($_SERVER['QUERY_STRING'])?'?'.$_SERVER['QUERY_STRING']:''));
}
$filters=['q'=>(string)($_GET['q']??''),'status'=>(string)($_GET['status']??'')];$result=admin_repository()->subscribers($filters,(int)($_GET['page']??1));$adminTitle='Newsletter';$adminPage='newsletter';$adminSection='Content';$adminActions='<div class="page-actions"><a class="button button--quiet" href="'.e(url('admin/export.php?type=newsletter')).'">Export CSV</a></div>';require __DIR__.'/_header.php';
?>
<form class="toolbar" method="get"><label class="field field--search"><span>Search</span><input type="search" name="q" value="<?= e($filters['q']) ?>" placeholder="Subscriber email"></label><label class="field"><span>Status</span><select name="status"><option value="">All</option><option value="subscribed" <?= $filters['status']==='subscribed'?'selected':'' ?>>Subscribed</option><option value="unsubscribed" <?= $filters['status']==='unsubscribed'?'selected':'' ?>>Unsubscribed</option></select></label><div class="toolbar-actions"><button class="button" type="submit">Filter</button><a class="button button--quiet" href="newsletter.php">Reset</a></div></form>
<section class="panel"><header class="panel__header"><h2><?= number_format($result['total']) ?> subscribers</h2></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Email</th><th>Subscribed</th><th>Updated</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($result['items']as$row): ?><tr><td><strong><?= e((string)$row['email']) ?></strong></td><td><?= e((string)$row['created_at']) ?></td><td><?= e((string)$row['updated_at']) ?></td><td><span class="<?= e(admin_status_class((string)$row['status'])) ?>"><?= e(format_status((string)$row['status'])) ?></span></td><td class="actions"><form method="post" data-confirm="Change this subscription status?"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><?php if($row['status']==='subscribed'): ?><button class="button button--small button--danger" name="status" value="unsubscribed">Unsubscribe</button><?php else: ?><button class="button button--small button--primary" name="status" value="subscribed">Reactivate</button><?php endif; ?></form></td></tr><?php endforeach; ?></tbody></table><?php if(!$result['items']): ?><div class="empty-state"><p>No subscribers found.</p></div><?php endif; ?></div></section><?= admin_pagination($result) ?>
<?php require __DIR__.'/_footer.php'; ?>
