<?php

declare(strict_types=1);

require __DIR__.'/_init.php';require_admin();$filters=['q'=>(string)($_GET['q']??''),'status'=>(string)($_GET['status']??''),'payment'=>(string)($_GET['payment']??''),'from'=>(string)($_GET['from']??''),'to'=>(string)($_GET['to']??'')];$result=admin_repository()->orders($filters,(int)($_GET['page']??1));
$adminTitle='Orders';$adminPage='orders';$adminSection='Sales';$adminActions='<div class="page-actions"><a class="button button--quiet" href="'.e(url('admin/export.php?type=orders')).'">Export CSV</a></div>';require __DIR__.'/_header.php';
?>
<form class="toolbar" method="get"><label class="field field--search"><span>Search</span><input type="search" name="q" value="<?= e($filters['q']) ?>" placeholder="Order, customer, or email"></label><label class="field"><span>Order status</span><select name="status"><option value="">All</option><?php foreach(['pending','processing','shipped','delivered','cancelled']as$status): ?><option value="<?= $status ?>" <?= $filters['status']===$status?'selected':'' ?>><?= e(format_status($status)) ?></option><?php endforeach; ?></select></label><label class="field"><span>Payment</span><select name="payment"><option value="">All</option><?php foreach(['pending','paid','failed','cod_pending']as$status): ?><option value="<?= $status ?>" <?= $filters['payment']===$status?'selected':'' ?>><?= e(format_status($status)) ?></option><?php endforeach; ?></select></label><label class="field"><span>From</span><input type="date" name="from" value="<?= e($filters['from']) ?>"></label><label class="field"><span>To</span><input type="date" name="to" value="<?= e($filters['to']) ?>"></label><div class="toolbar-actions"><button class="button" type="submit">Filter</button><a class="button button--quiet" href="orders.php">Reset</a></div></form>
<section class="panel"><header class="panel__header"><h2><?= number_format($result['total']) ?> orders</h2></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Order</th><th>Customer</th><th>Email</th><th>Date</th><th class="numeric">Items</th><th class="numeric">Total</th><th>Payment method</th><th>Payment</th><th>Order status</th></tr></thead><tbody><?php foreach($result['items']as$order): ?><tr><td><a href="<?= e(url('admin/order.php?id='.(int)$order['id'])) ?>"><strong><?= e((string)$order['order_number']) ?></strong></a></td><td><?= e($order['customer_first_name'].' '.$order['customer_last_name']) ?></td><td><?= e((string)$order['customer_email']) ?></td><td><?= e(date('M j, Y H:i',strtotime((string)$order['placed_at']))) ?></td><td class="numeric"><?= (int)$order['item_count'] ?></td><td class="numeric"><strong><?= admin_money($order['total']) ?></strong></td><td><?= e(format_status((string)$order['payment_method'])) ?></td><td><span class="<?= e(admin_status_class((string)$order['payment_status'])) ?>"><?= e(format_status((string)$order['payment_status'])) ?></span></td><td><span class="<?= e(admin_status_class((string)$order['order_status'])) ?>"><?= e(format_status((string)$order['order_status'])) ?></span></td></tr><?php endforeach; ?></tbody></table><?php if(!$result['items']): ?><div class="empty-state"><div><strong>No orders found</strong><p>Adjust the filters.</p></div></div><?php endif; ?></div></section><?= admin_pagination($result) ?>
<?php require __DIR__.'/_footer.php'; ?>
