<?php

declare(strict_types=1);

require __DIR__.'/_init.php';$admin=require_admin();
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{
        admin_post_guard();$action=(string)($_POST['action']??'');$id=(int)($_POST['id']??0);
        if($action==='archive'&&$id>0){admin_service()->archiveProduct($id);flash('success','Product archived.');}
        elseif($action==='delete'&&$id>0){if(!admin_repository()->deleteProductIfSafe($id))throw new DomainException('This product has order or review history and must be archived instead.');admin_repository()->audit((int)$admin['id'],'product.delete','product',$id,'Deleted unreferenced product.');flash('success','Product deleted.');}
        elseif(in_array($action,['bulk_activate','bulk_archive'],true)){
            $ids=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['selected']??[])))));if($ids===[])throw new DomainException('Select at least one product.');
            $marks=implode(',',array_fill(0,count($ids),'?'));$status=$action==='bulk_activate'?'active':'archived';$statement=db()->prepare('UPDATE products SET status=?,is_active=? WHERE id IN ('.$marks.')');$statement->execute(array_merge([$status,$status==='active'?1:0],$ids));
            admin_repository()->audit((int)$admin['id'],'product.bulk','product',null,ucfirst($status).' '.count($ids).' products.');flash('success',count($ids).' products updated.');
        }else throw new DomainException('Invalid product action.');
    }catch(Throwable$exception){admin_flash_exception($exception);}admin_redirect('products.php'.(!empty($_SERVER['QUERY_STRING'])?'?'.$_SERVER['QUERY_STRING']:''));
}
$filters=['q'=>(string)($_GET['q']??''),'status'=>(string)($_GET['status']??''),'category_id'=>(string)($_GET['category_id']??''),'collection_id'=>(string)($_GET['collection_id']??''),'sort'=>(string)($_GET['sort']??'updated')];
$result=admin_repository()->products($filters,(int)($_GET['page']??1));$categories=admin_repository()->categories();$collections=admin_repository()->collections();
$adminTitle='Products';$adminPage='products';$adminSection='Store';$adminActions='<div class="page-actions"><a class="button button--primary" href="'.e(url('admin/product-edit.php')).'">Add product</a></div>';require __DIR__.'/_header.php';
?>
<form class="toolbar" method="get"><label class="field field--search"><span>Search</span><input type="search" name="q" value="<?= e($filters['q']) ?>" placeholder="Name, slug, or SKU"></label>
<label class="field"><span>Status</span><select name="status"><option value="">All statuses</option><?php foreach(['active','draft','archived']as$status): ?><option value="<?= $status ?>" <?= $filters['status']===$status?'selected':'' ?>><?= e(format_status($status)) ?></option><?php endforeach; ?></select></label>
<label class="field"><span>Category</span><select name="category_id"><option value="">All categories</option><?php foreach($categories as$row): ?><option value="<?= (int)$row['id'] ?>" <?= (string)$row['id']===$filters['category_id']?'selected':'' ?>><?= e((string)$row['name']) ?></option><?php endforeach; ?></select></label>
<label class="field"><span>Collection</span><select name="collection_id"><option value="">All collections</option><?php foreach($collections as$row): ?><option value="<?= (int)$row['id'] ?>" <?= (string)$row['id']===$filters['collection_id']?'selected':'' ?>><?= e((string)$row['name']) ?></option><?php endforeach; ?></select></label>
<label class="field"><span>Sort</span><select name="sort"><option value="updated">Recently updated</option><option value="newest" <?= $filters['sort']==='newest'?'selected':'' ?>>Newest</option><option value="name" <?= $filters['sort']==='name'?'selected':'' ?>>Name</option><option value="price" <?= $filters['sort']==='price'?'selected':'' ?>>Price</option><option value="stock" <?= $filters['sort']==='stock'?'selected':'' ?>>Low stock</option></select></label>
<div class="toolbar-actions"><button class="button" type="submit">Filter</button><a class="button button--quiet" href="products.php">Reset</a></div></form>
<form method="post" id="bulk-products"><?= csrf_field() ?><section class="panel"><header class="panel__header"><h2><?= number_format($result['total']) ?> products</h2><div class="page-actions"><button class="button button--small" type="submit" name="action" value="bulk_activate">Activate</button><button class="button button--small" type="submit" name="action" value="bulk_archive" data-confirm="Archive selected products?">Archive</button></div></header><div class="table-wrap"><table class="data-table"><thead><tr><th><span class="sr-only">Select</span></th><th>Product</th><th>Category</th><th>Collection</th><th>Status</th><th class="numeric">Price</th><th class="numeric">Stock</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>
<?php foreach($result['items']as$product): ?><tr><td><input type="checkbox" name="selected[]" value="<?= (int)$product['id'] ?>" aria-label="Select <?= e((string)$product['name']) ?>"></td><td><div style="display:flex;align-items:center;gap:.7rem"><?php if($product['image_path']): ?><img class="thumb" src="<?= e(media_url((string)$product['image_path'])) ?>" alt=""><?php endif; ?><div><strong><?= e((string)$product['name']) ?></strong><small><?= e((string)$product['slug']) ?> · <?= (int)$product['variant_count'] ?> variants</small></div></div></td><td><?= e((string)$product['category_name']) ?></td><td><?= e((string)$product['collection_name']) ?></td><td><span class="<?= e(admin_status_class((string)$product['status'])) ?>"><?= e(format_status((string)$product['status'])) ?></span></td><td class="numeric"><?= admin_money($product['sale_price']??$product['price']) ?></td><td class="numeric"><strong><?= (int)$product['stock_total'] ?></strong></td><td class="actions"><a class="button button--small button--quiet" href="<?= e(url('admin/product-edit.php?id='.(int)$product['id'])) ?>">Edit</a><button class="button button--small button--quiet" type="submit" name="action" value="archive" formaction="products.php" formmethod="post" onclick="this.form.querySelector('[name=id]').value='<?= (int)$product['id'] ?>'">Archive</button></td></tr><?php endforeach; ?>
</tbody></table><?php if(!$result['items']): ?><div class="empty-state"><div><strong>No products found</strong><p>Adjust the filters or add a product.</p></div></div><?php endif; ?></div></section><input type="hidden" name="id" value=""></form><?= admin_pagination($result) ?>
<?php require __DIR__.'/_footer.php'; ?>
