<?php

declare(strict_types=1);

require __DIR__.'/_init.php';$admin=require_admin();$id=filter_var($_GET['id']??$_POST['product_id']??null,FILTER_VALIDATE_INT)?:null;$tab=(string)($_GET['tab']??'details');if(!in_array($tab,['details','variants','images'],true))$tab='details';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{
        admin_post_guard();$action=(string)($_POST['action']??'save_product');
        if($action==='save_product'){$id=admin_service()->saveProduct($_POST,$id);flash('success','Product saved.');$tab='details';}
        elseif($action==='save_variant'){if(!$id)throw new DomainException('Save the product first.');admin_service()->saveVariant($_POST,filter_var($_POST['variant_id']??null,FILTER_VALIDATE_INT)?:null);flash('success','Variant saved.');$tab='variants';}
        elseif($action==='delete_variant'){if(!admin_repository()->deleteVariantIfSafe((int)($_POST['variant_id']??0)))throw new DomainException('This variant is referenced by a cart or order. Disable it instead.');admin_repository()->audit((int)$admin['id'],'variant.delete','variant',(int)$_POST['variant_id'],'Deleted unreferenced variant.');flash('success','Variant deleted.');$tab='variants';}
        elseif($action==='upload_images'){if(!$id)throw new DomainException('Save the product first.');$count=admin_service()->uploadImages($id,$_FILES['images']??[],(string)($_POST['alt_text']??''),(string)($_POST['color_slug']??''));flash('success',$count.' image'.($count===1?'':'s').' uploaded.');$tab='images';}
        elseif($action==='update_image'){admin_service()->updateImage((int)($_POST['image_id']??0),$_POST);flash('success','Image updated.');$tab='images';}
        elseif($action==='delete_image'){admin_service()->deleteImage((int)($_POST['image_id']??0));flash('success','Image removed.');$tab='images';}
        else throw new DomainException('Invalid product action.');
    }catch(Throwable$exception){admin_flash_exception($exception);}admin_redirect('product-edit.php'.($id?'?id='.$id.'&tab='.$tab:''));
}
$product=$id?admin_repository()->product((int)$id):null;if($id&&!$product){http_response_code(404);exit('Product not found.');}$categories=admin_repository()->categories();$collections=admin_repository()->collections();
$editVariantId=filter_var($_GET['variant']??null,FILTER_VALIDATE_INT)?:null;$editVariant=null;if($editVariantId&&$product)foreach($product['variants']as$row)if((int)$row['id']===$editVariantId)$editVariant=$row;
$adminTitle=$product?'Edit '.$product['name']:'New product';$adminPage='products';$adminSection='Store';$adminActions='<div class="page-actions"><a class="button button--quiet" href="'.e(url('admin/products.php')).'">Back to products</a>'.($product?'<a class="button" target="_blank" rel="noopener" href="'.e(url('product.php?slug='.rawurlencode((string)$product['slug']))).'">View product ↗</a>':'').'</div>';require __DIR__.'/_header.php';
$keywords='';if($product){$decoded=json_decode((string)($product['keywords']??'[]'),true);$keywords=is_array($decoded)?implode(', ',$decoded):'';}
?>
<?php if($product): ?><nav class="product-editor-nav" aria-label="Product editor"><a class="<?= $tab==='details'?'is-active':'' ?>" href="?id=<?= (int)$product['id'] ?>&tab=details">Details</a><a class="<?= $tab==='variants'?'is-active':'' ?>" href="?id=<?= (int)$product['id'] ?>&tab=variants">Variants · <?= count($product['variants']) ?></a><a class="<?= $tab==='images'?'is-active':'' ?>" href="?id=<?= (int)$product['id'] ?>&tab=images">Images · <?= count($product['images']) ?></a></nav><?php endif; ?>
<?php if($tab==='details'): ?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_product"><?php if($id): ?><input type="hidden" name="product_id" value="<?= (int)$id ?>"><?php endif; ?><div class="form-grid"><div><section class="form-section form-stack"><h2>Product information</h2><label class="field"><span>Name</span><input id="product-name" data-slug-source="#product-slug" name="name" value="<?= e((string)($product['name']??'')) ?>" required></label><label class="field"><span>Slug</span><input id="product-slug" name="slug" value="<?= e((string)($product['slug']??'')) ?>" pattern="[a-z0-9-]+" required><small>Changing an existing slug changes its storefront URL.</small></label><label class="field"><span>Short description</span><textarea name="short_description" rows="3"><?= e((string)($product['short_description']??'')) ?></textarea></label><label class="field"><span>Description</span><textarea name="description" required><?= e((string)($product['description']??'')) ?></textarea></label><div class="field-row"><label class="field"><span>Materials</span><textarea name="materials"><?= e((string)($product['materials']??'')) ?></textarea></label><label class="field"><span>Care</span><textarea name="care"><?= e((string)($product['care']??'')) ?></textarea></label></div></section>
<section class="form-section form-stack"><h2>Search and merchandising</h2><label class="field"><span>Keywords</span><input name="keywords" value="<?= e($keywords) ?>"><small>Comma-separated terms used by storefront search.</small></label><div class="field-row"><label class="field"><span>Meta title</span><input name="meta_title" maxlength="190" value="<?= e((string)($product['meta_title']??'')) ?>"></label><label class="field"><span>Meta description</span><input name="meta_description" maxlength="320" value="<?= e((string)($product['meta_description']??'')) ?>"></label></div></section></div>
<aside><section class="form-section form-stack sticky-card"><h2>Publishing</h2><label class="field"><span>Status</span><select name="status"><?php foreach(['draft','active','archived']as$status): ?><option value="<?= $status ?>" <?= ($product['status']??'draft')===$status?'selected':'' ?>><?= e(format_status($status)) ?></option><?php endforeach; ?></select></label><label class="field"><span>Category</span><select name="category_id" required><option value="">Choose</option><?php foreach($categories as$row): ?><option value="<?= (int)$row['id'] ?>" <?= (int)($product['category_id']??0)===(int)$row['id']?'selected':'' ?>><?= e((string)$row['name']) ?></option><?php endforeach; ?></select></label><label class="field"><span>Collection</span><select name="collection_id" required><option value="">Choose</option><?php foreach($collections as$row): ?><option value="<?= (int)$row['id'] ?>" <?= (int)($product['collection_id']??0)===(int)$row['id']?'selected':'' ?>><?= e((string)$row['name']) ?></option><?php endforeach; ?></select></label><div class="field-row"><label class="field"><span>Base price</span><input type="number" min="0" step="0.01" name="price" value="<?= e((string)($product['price']??'')) ?>" required></label><label class="field"><span>Sale price</span><input type="number" min="0" step="0.01" name="sale_price" value="<?= e((string)($product['sale_price']??'')) ?>"></label></div><div class="field-row"><label class="field"><span>Label</span><input name="label" maxlength="40" value="<?= e((string)($product['label']??'')) ?>"></label><label class="field"><span>Popularity</span><input type="number" min="0" max="100" name="popularity" value="<?= e((string)($product['popularity']??0)) ?>"></label></div><label class="check-field"><input type="checkbox" name="is_featured" value="1" <?= !empty($product['is_featured'])?'checked':'' ?>> Featured product</label><div class="form-footer"><button class="button button--primary" type="submit">Save product</button></div></section></aside></div></form>
<?php elseif($tab==='variants'&&$product): ?><div class="form-grid"><section class="panel"><header class="panel__header"><h2>Variant matrix</h2><span><?= count($product['variants']) ?> variants</span></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Color</th><th>Size</th><th>SKU</th><th class="numeric">Stock</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($product['variants']as$row): ?><tr><td><span style="display:inline-block;width:.7rem;height:.7rem;background:<?= e((string)$row['color_hex']) ?>;border:1px solid #555;margin-right:.4rem"></span><?= e((string)$row['color_name']) ?></td><td><?= e((string)$row['size']) ?></td><td><strong><?= e((string)$row['sku']) ?></strong></td><td class="numeric <?= (int)$row['stock_quantity']===0?'stock-out':((int)$row['stock_quantity']<=(int)setting('low_stock_threshold','5')?'stock-low':'') ?>"><?= (int)$row['stock_quantity'] ?></td><td><span class="<?= e(admin_status_class((bool)$row['is_active']?'active':'disabled')) ?>"><?= (bool)$row['is_active']?'Active':'Disabled' ?></span></td><td class="actions"><a class="button button--small button--quiet" href="?id=<?= (int)$id ?>&tab=variants&variant=<?= (int)$row['id'] ?>">Edit</a><form method="post" data-confirm="Delete this unreferenced variant?"><?= csrf_field() ?><input type="hidden" name="product_id" value="<?= (int)$id ?>"><input type="hidden" name="variant_id" value="<?= (int)$row['id'] ?>"><button class="button button--small button--danger" name="action" value="delete_variant">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>
<aside><form class="form-section form-stack sticky-card" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_variant"><input type="hidden" name="product_id" value="<?= (int)$id ?>"><input type="hidden" name="variant_id" value="<?= (int)($editVariant['id']??0) ?>"><h2><?= $editVariant?'Edit':'Add' ?> variant</h2><div class="field-row"><label class="field"><span>Color name</span><input name="color_name" value="<?= e((string)($editVariant['color_name']??'')) ?>" required></label><label class="field"><span>Color slug</span><input name="color_slug" value="<?= e((string)($editVariant['color_slug']??'')) ?>"></label></div><div class="field-row"><label class="field"><span>Hex</span><input name="color_hex" value="<?= e((string)($editVariant['color_hex']??'#0A0A0A')) ?>" pattern="#[0-9A-Fa-f]{6}" required></label><label class="field"><span>Size</span><input name="size" value="<?= e((string)($editVariant['size']??'')) ?>" required></label></div><label class="field"><span>SKU</span><input name="sku" value="<?= e((string)($editVariant['sku']??'')) ?>" required></label><label class="field"><span>Stock</span><input type="number" min="0" name="stock_quantity" value="<?= e((string)($editVariant['stock_quantity']??0)) ?>" required></label><label class="field"><span>Associated image</span><select name="image_id"><option value="">Automatic by color</option><?php foreach($product['images']as$image): ?><option value="<?= (int)$image['id'] ?>" <?= (int)($editVariant['image_id']??0)===(int)$image['id']?'selected':'' ?>>#<?= (int)$image['id'] ?> · <?= e((string)($image['alt_text']?:$image['path'])) ?></option><?php endforeach; ?></select></label><label class="check-field"><input type="checkbox" name="is_active" value="1" <?= !isset($editVariant['is_active'])||$editVariant['is_active']?'checked':'' ?>> Active</label><div class="form-footer"><?php if($editVariant): ?><a class="button button--quiet" href="?id=<?= (int)$id ?>&tab=variants">Cancel</a><?php endif; ?><button class="button button--primary" type="submit">Save variant</button></div></form></aside></div>
<?php elseif($tab==='images'&&$product): ?><section class="form-section"><h2>Upload product images</h2><form method="post" enctype="multipart/form-data" class="form-stack"><?= csrf_field() ?><input type="hidden" name="action" value="upload_images"><input type="hidden" name="product_id" value="<?= (int)$id ?>"><div class="field-row--3 field-row"><label class="field"><span>Images</span><input data-image-input type="file" name="images[]" accept="image/jpeg,image/png,image/webp" multiple required><small>JPG, PNG, or WebP · max 8 MB each.</small></label><label class="field"><span>Shared alt text</span><input name="alt_text" maxlength="255"></label><label class="field"><span>Color slug</span><input name="color_slug" placeholder="Optional"></label></div><div class="upload-preview" data-upload-preview aria-hidden="true"></div><div class="form-footer"><button class="button button--primary" type="submit">Upload images</button></div></form></section><section class="form-section"><h2>Image library</h2><div class="image-grid"><?php foreach($product['images']as$image): ?><article class="image-card"><img src="<?= e(media_url((string)$image['path'])) ?>" alt="<?= e((string)$image['alt_text']) ?>"><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="update_image"><input type="hidden" name="product_id" value="<?= (int)$id ?>"><input type="hidden" name="image_id" value="<?= (int)$image['id'] ?>"><label class="field"><span>Alt text</span><input name="alt_text" value="<?= e((string)$image['alt_text']) ?>"></label><div class="field-row"><label class="field"><span>Role</span><select name="role"><?php foreach(['gallery','campaign','detail']as$role): ?><option value="<?= $role ?>" <?= $image['role']===$role?'selected':'' ?>><?= ucfirst($role) ?></option><?php endforeach; ?></select></label><label class="field"><span>Order</span><input type="number" min="0" name="sort_order" value="<?= (int)$image['sort_order'] ?>"></label></div><label class="field"><span>Color slug</span><input name="color_slug" value="<?= e((string)$image['color_slug']) ?>"></label><label class="check-field"><input type="checkbox" name="is_primary" value="1" <?= $image['is_primary']?'checked':'' ?>> Primary image</label><button class="button button--small" type="submit">Save image</button></form><form method="post" data-confirm="Remove this image? Runtime uploads are deleted from disk."><?= csrf_field() ?><input type="hidden" name="action" value="delete_image"><input type="hidden" name="product_id" value="<?= (int)$id ?>"><input type="hidden" name="image_id" value="<?= (int)$image['id'] ?>"><button class="button button--small button--danger" type="submit">Remove</button></form></article><?php endforeach; ?></div><?php if(!$product['images']): ?><div class="empty-state"><p>No images yet.</p></div><?php endif; ?></section><?php endif; ?>
<?php require __DIR__.'/_footer.php'; ?>
