<?php

declare(strict_types=1);

require __DIR__.'/_init.php';$admin=require_admin();
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{admin_post_guard();$id=(int)($_POST['id']??0);$status=(string)($_POST['status']??'');if(!in_array($status,['approved','rejected','hidden'],true))throw new DomainException('Choose a valid moderation action.');admin_repository()->updateReviewStatus($id,$status);admin_repository()->audit((int)$admin['id'],'review.moderate','review',$id,'Review changed to '.$status.'.');flash('success','Review marked '.format_status($status).'.');}
    catch(Throwable$exception){admin_flash_exception($exception);}admin_redirect('reviews.php'.(!empty($_SERVER['QUERY_STRING'])?'?'.$_SERVER['QUERY_STRING']:''));
}
$filters=['q'=>(string)($_GET['q']??''),'status'=>(string)($_GET['status']??'pending')];$result=admin_repository()->reviews($filters,(int)($_GET['page']??1));$adminTitle='Reviews';$adminPage='reviews';$adminSection='Content';require __DIR__.'/_header.php';
?>
<form class="toolbar" method="get"><label class="field field--search"><span>Search</span><input type="search" name="q" value="<?= e($filters['q']) ?>" placeholder="Product, customer, email, or review"></label><label class="field"><span>Status</span><select name="status"><option value="">All reviews</option><?php foreach(['pending','approved','rejected','hidden']as$status): ?><option value="<?= $status ?>" <?= $filters['status']===$status?'selected':'' ?>><?= e(format_status($status)) ?></option><?php endforeach; ?></select></label><div class="toolbar-actions"><button class="button" type="submit">Filter</button><a class="button button--quiet" href="reviews.php?status=pending">Reset</a></div></form>
<section class="panel"><header class="panel__header"><h2><?= number_format($result['total']) ?> reviews</h2></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Customer</th><th>Product</th><th>Rating</th><th>Review</th><th>Date</th><th>Purchase</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($result['items']as$row): ?><tr><td><strong><?= e((string)$row['customer_name']) ?></strong><small><?= e((string)$row['email']) ?></small></td><td><a href="<?= e(url('admin/product-edit.php?id='.(int)$row['product_id'])) ?>"><?= e((string)$row['product_name']) ?></a></td><td><strong aria-label="<?= (int)$row['rating'] ?> out of 5"><?= str_repeat('★',(int)$row['rating']) ?></strong></td><td style="max-width:28rem"><?= nl2br(e((string)$row['content'])) ?></td><td><?= e(date('M j, Y',strtotime((string)$row['created_at']))) ?></td><td><?= $row['verified_purchase']?'<span class="status status--active">Verified</span>':'—' ?></td><td><span class="<?= e(admin_status_class((string)$row['status'])) ?>"><?= e(format_status((string)$row['status'])) ?></span></td><td class="actions"><form method="post"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><button class="button button--small button--primary" name="status" value="approved">Approve</button><button class="button button--small button--quiet" name="status" value="hidden">Hide</button><button class="button button--small button--danger" name="status" value="rejected">Reject</button></form></td></tr><?php endforeach; ?></tbody></table><?php if(!$result['items']): ?><div class="empty-state"><div><strong>Queue clear</strong><p>No reviews match these filters.</p></div></div><?php endif; ?></div></section><?= admin_pagination($result) ?>
<?php require __DIR__.'/_footer.php'; ?>
